TESTER_CYCLE=20
GETTER_CYCLE=20
TESTER_ENABLED=True
GETTER_ENABLED=True
API_ENABLED=True
API_PORT=5555
API_HOST='127.0.0.1'

VALID_STSTUS_CODES=[200,302]
TEST_URL='http://www.baidu.com'
BATCH_TEST_SIZE=10

POOL_UPPER_THRESHOLD=10000

MAX_SCORE=100
MIN_SOCRE=0
INITIAL_SCORE=10
REDIS_HOST='localhost'
REDIS_PORT=6379
REDIS_PASSWORD=None
REDIS_KEY='proxies'
